=== aayusharora6896/Fandango/arora_ayush_part_1/fandango.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT fandango (date, city+)> 
<!ELEMENT date (#PCDATA)>
<!ELEMENT city (theater+)>
<!ATTLIST city cname CDATA #REQUIRED>
<!ELEMENT theater (name, address, movie+)>
<!ATTLIST theater tname CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT movie (details+)>
<!ATTLIST movie number CDATA #REQUIRED>
<!ELEMENT details (html, title, desc, desc1, shows)>
<!ELEMENT html (img)>
<!ATTLIST html xmlns CDATA #REQUIRED>
<!ELEMENT img (#PCDATA)>
<!ATTLIST img src CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT desc (rating, runtime)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT runtime (#PCDATA)>
<!ELEMENT desc1 (captioning, accessibility)>
<!ELEMENT captioning (#PCDATA)>
<!ELEMENT accessibility (#PCDATA)>
<!ELEMENT shows (showTimings+)>
<!ELEMENT showTimings (#PCDATA)>
<!ATTLIST showTimings snumber CDATA #REQUIRED>

=== aayusharora6896/Fandango/arora_ayush_part_1/fandango.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet snumber="text/css" href="fandango.css"?>
<!DOCTYPE fandango SYSTEM "fandango.dtd">
<fandango>
    <date> Date of Show - 09/26/2018 </date>
    <city cname="Rochester, NY">
        <theater tname="theater1">
            <name> Movies 10 </name>
            <address> 2613 West Henrietta Road, Rochester, NY  14623 </address>
            <movie number="theater1movie1">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/11.jpg"/>
                    </html>
                    <title> The Happytime Murders </title>
                    <desc>
                        <rating> (R) </rating>
                        <runtime> 1 hr 31 mins </runtime>
                    </desc>
                    <desc1>    
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 12:25pm</showTimings>
                        <showTimings snumber="show2"> 05:45pm</showTimings>
                        <showTimings snumber="show3"> 07:50pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie2">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/12.jpg"/>
                    </html>
                    <title> Alpha </title>
                    <desc>
                        <rating> (PG-13) </rating>
                        <runtime> 1 hr 37 mins </runtime>
                    </desc>
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>    
                    <shows>
                        <showTimings snumber="show1"> 12:20pm</showTimings>
                        <showTimings snumber="show2"> 02:35pm</showTimings>
                        <showTimings snumber="show3"> 04:50pm</showTimings>
                        <showTimings snumber="show4"> 07:15pm</showTimings>
                    </shows>
                </details>        
            </movie>
            <movie number="theater1movie3">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/13.jpg"/>
                    </html>
                    <title> Mile 22 </title>
                    <desc>
                        <rating> (R) </rating>
                        <runtime> 1 hr 35 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 12:05pm</showTimings>
                        <showTimings snumber="show2"> 03:35pm</showTimings>
                        <showTimings snumber="show3"> 07:25pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie4">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/14.jpg"/>
                    </html>
                    <title> Slender Man </title>
                    <desc>
                        <rating> (PG-13) </rating>
                        <runtime> 1 hr 33 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 07:40pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie5">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/15.png"/>
                    </html>
                    <title> The Spy Who Dumped Me </title>
                    <desc>
                        <rating> (R) </rating>
                        <runtime> 1 hr 56 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 02:30pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie6">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/16.jpg"/>
                    </html>
                    <title> Teen Titans Go! To the Movies </title>
                    <desc>
                        <rating> (PG) </rating>
                        <runtime> 1 hr 27 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 01:00pm</showTimings>
                        <showTimings snumber="show2"> 03:10pm</showTimings>
                        <showTimings snumber="show3"> 05:15pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie7">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/17.jpg"/>
                    </html>
                    <title> Mamma Mia! Here We Go Again </title>
                    <desc>
                        <rating> (PG-13) </rating>
                        <runtime> 1 hr 54 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 01:50pm</showTimings>
                        <showTimings snumber="show2"> 04:20pm</showTimings>
                        <showTimings snumber="show3"> 06:50pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie8">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/18.jpg"/>
                    </html>
                    <title> The Equalizer 2 </title>
                    <desc>
                        <rating> (R) </rating>
                        <runtime> 2 hr 01 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 02:15pm</showTimings>
                        <showTimings snumber="show2"> 04:55pm</showTimings>
                        <showTimings snumber="show3"> 07:30pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie9">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/19.jpg"/>
                    </html>
                    <title> Hotel Transylvania 3: Summer Vacation </title>
                    <desc>
                        <rating> (PG) </rating>
                        <runtime> 1 hr 25 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 12:10pm</showTimings>
                        <showTimings snumber="show2"> 02:25pm</showTimings>
                        <showTimings snumber="show3"> 04:40pm</showTimings>
                        <showTimings snumber="show4"> 07:00pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie10">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/110.jpg"/>
                    </html>
                    <title> Skyscraper (2018) </title>
                    <desc>
                        <rating> (PG-13) </rating>
                        <runtime> 1 hr 42 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 06:40pm</showTimings>
                    </shows>
                </details>    
            </movie>
            <movie number="theater1movie11">
                <details>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                        <img src = "img/111.jpg"/>
                    </html>
                    <title> Uncle Drew  </title>
                    <desc>
                        <rating> (PG-13) </rating>
                        <runtime> 1 hr 43 mins </runtime>
                    </desc> 
                    <desc1>
                        <captioning/>
                        <accessibility/>
                    </desc1>
                    <shows>
                        <showTimings snumber="show1"> 01:15pm</showTimings>
                        <showTimings snumber="show2"> 05:05pm</showTimings>
                    </shows>
                </details>    
            </movie>
